// GENERATED by scripts/gen-grinders.mjs from data/grinders/honestcoffeeguide-grinders.json — do not edit by hand.
// Curated subset (Phase 3 feature #3): scraped grinders that carry both a
// max-click count and a micron span, so the click-based model can derive
// µm/click. Stepless/no-click grinders and the hand-tuned seed are excluded.
export const SCRAPED_GRINDERS = [
  {
    "id": "hcg-baratza-encore",
    "brand": "Baratza",
    "model": "Encore",
    "clicks": 40,
    "umPerClick": 30,
    "scraped": true
  },
  {
    "id": "hcg-baratza-encore-esp",
    "brand": "Baratza",
    "model": "Encore ESP",
    "clicks": 40,
    "umPerClick": 34.5,
    "scraped": true
  },
  {
    "id": "hcg-baratza-encore-esp-pro",
    "brand": "Baratza",
    "model": "Encore ESP Pro",
    "clicks": 60,
    "umPerClick": 19.8,
    "scraped": true
  },
  {
    "id": "hcg-baratza-maestro",
    "brand": "Baratza",
    "model": "Maestro",
    "clicks": 40,
    "umPerClick": 25.3,
    "scraped": true
  },
  {
    "id": "hcg-baratza-sette-270",
    "brand": "Baratza",
    "model": "Sette 270",
    "clicks": 31,
    "umPerClick": 30.6,
    "scraped": true
  },
  {
    "id": "hcg-baratza-sette-30",
    "brand": "Baratza",
    "model": "Sette 30",
    "clicks": 31,
    "umPerClick": 30.6,
    "scraped": true
  },
  {
    "id": "hcg-bentwood-vertical-63",
    "brand": "Bentwood",
    "model": "Vertical 63",
    "clicks": 63,
    "umPerClick": 22.2,
    "scraped": true
  },
  {
    "id": "hcg-breville-sage-the-dose-control-pro",
    "brand": "Breville",
    "model": "(Sage) The Dose Control Pro",
    "clicks": 60,
    "umPerClick": 13.7,
    "scraped": true
  },
  {
    "id": "hcg-breville-sage-the-smart-grinder-pro",
    "brand": "Breville",
    "model": "(Sage) The Smart Grinder Pro",
    "clicks": 60,
    "umPerClick": 13.7,
    "scraped": true
  },
  {
    "id": "hcg-capresso-infinity",
    "brand": "Capresso",
    "model": "Infinity",
    "clicks": 16,
    "umPerClick": 76.3,
    "scraped": true
  },
  {
    "id": "hcg-capresso-infinity-plus",
    "brand": "Capresso",
    "model": "Infinity Plus",
    "clicks": 16,
    "umPerClick": 76.3,
    "scraped": true
  },
  {
    "id": "hcg-compak-k3-push",
    "brand": "Compak",
    "model": "K3 Push",
    "clicks": 30,
    "umPerClick": 43,
    "scraped": true
  },
  {
    "id": "hcg-compak-k3-touch",
    "brand": "Compak",
    "model": "K3 Touch",
    "clicks": 30,
    "umPerClick": 43,
    "scraped": true
  },
  {
    "id": "hcg-compak-k3-touch-advanced",
    "brand": "Compak",
    "model": "K3 Touch Advanced",
    "clicks": 30,
    "umPerClick": 43,
    "scraped": true
  },
  {
    "id": "hcg-cuisinart-cbm-18",
    "brand": "Cuisinart",
    "model": "CBM-18",
    "clicks": 13,
    "umPerClick": 107.7,
    "scraped": true
  },
  {
    "id": "hcg-cuisinart-dbm-8",
    "brand": "Cuisinart",
    "model": "DBM-8",
    "clicks": 18,
    "umPerClick": 77.8,
    "scraped": true
  },
  {
    "id": "hcg-de-longhi-kg79",
    "brand": "De'Longhi",
    "model": "KG79",
    "clicks": 17,
    "umPerClick": 73.5,
    "scraped": true
  },
  {
    "id": "hcg-de-longhi-kg89",
    "brand": "De'Longhi",
    "model": "KG89",
    "clicks": 17,
    "umPerClick": 73.5,
    "scraped": true
  },
  {
    "id": "hcg-eureka-atom-60",
    "brand": "Eureka",
    "model": "Atom 60",
    "clicks": 30,
    "umPerClick": 46.7,
    "scraped": true
  },
  {
    "id": "hcg-eureka-atom-75",
    "brand": "Eureka",
    "model": "Atom 75",
    "clicks": 30,
    "umPerClick": 46.7,
    "scraped": true
  },
  {
    "id": "hcg-eureka-mignon-oro",
    "brand": "Eureka",
    "model": "Mignon Oro",
    "clicks": 30,
    "umPerClick": 31.7,
    "scraped": true
  },
  {
    "id": "hcg-eureka-mignon-oro-xl",
    "brand": "Eureka",
    "model": "Mignon Oro XL",
    "clicks": 30,
    "umPerClick": 31.7,
    "scraped": true
  },
  {
    "id": "hcg-fellow-ode-brew-grinder-gen-2",
    "brand": "Fellow",
    "model": "Ode Brew Grinder Gen 2",
    "clicks": 11,
    "umPerClick": 105.5,
    "scraped": true
  },
  {
    "id": "hcg-fuji-royal-r-220",
    "brand": "Fuji",
    "model": "Royal R-220",
    "clicks": 10,
    "umPerClick": 109,
    "scraped": true
  },
  {
    "id": "hcg-handground-precision-coffee-grinder",
    "brand": "Handground",
    "model": "Precision Coffee Grinder",
    "clicks": 8,
    "umPerClick": 175,
    "scraped": true
  },
  {
    "id": "hcg-hario-mini-mill-plus",
    "brand": "Hario",
    "model": "Mini Mill PLUS",
    "clicks": 20,
    "umPerClick": 70,
    "scraped": true
  },
  {
    "id": "hcg-hario-mini-mill-slim",
    "brand": "Hario",
    "model": "Mini Mill Slim",
    "clicks": 20,
    "umPerClick": 70,
    "scraped": true
  },
  {
    "id": "hcg-hario-mini-mill-slim-pro",
    "brand": "Hario",
    "model": "Mini Mill Slim PRO",
    "clicks": 20,
    "umPerClick": 70,
    "scraped": true
  },
  {
    "id": "hcg-hario-skerton",
    "brand": "Hario",
    "model": "Skerton",
    "clicks": 10,
    "umPerClick": 140,
    "scraped": true
  },
  {
    "id": "hcg-hario-skerton-plus",
    "brand": "Hario",
    "model": "Skerton PLUS",
    "clicks": 10,
    "umPerClick": 140,
    "scraped": true
  },
  {
    "id": "hcg-hario-skerton-pro",
    "brand": "Hario",
    "model": "Skerton PRO",
    "clicks": 10,
    "umPerClick": 140,
    "scraped": true
  },
  {
    "id": "hcg-hario-smart-g",
    "brand": "Hario",
    "model": "Smart-G",
    "clicks": 14,
    "umPerClick": 100,
    "scraped": true
  },
  {
    "id": "hcg-javapresse-manual-coffee-grinder",
    "brand": "JavaPresse",
    "model": "Manual Coffee Grinder",
    "clicks": 20,
    "umPerClick": 70,
    "scraped": true
  },
  {
    "id": "hcg-kitchenaid-artisan-coffee-grinder-5kcg0702",
    "brand": "KitchenAid",
    "model": "Artisan Coffee Grinder 5KCG0702",
    "clicks": 8,
    "umPerClick": 133.8,
    "scraped": true
  },
  {
    "id": "hcg-krups-gvx1",
    "brand": "Krups",
    "model": "GVX1",
    "clicks": 17,
    "umPerClick": 55.9,
    "scraped": true
  },
  {
    "id": "hcg-krups-gvx2",
    "brand": "Krups",
    "model": "GVX2",
    "clicks": 17,
    "umPerClick": 55.9,
    "scraped": true
  },
  {
    "id": "hcg-krups-gx5000",
    "brand": "Krups",
    "model": "GX5000",
    "clicks": 12,
    "umPerClick": 115,
    "scraped": true
  },
  {
    "id": "hcg-krups-gx6000",
    "brand": "Krups",
    "model": "GX6000",
    "clicks": 16,
    "umPerClick": 87.5,
    "scraped": true
  },
  {
    "id": "hcg-mahlk-nig-ek43-0-16",
    "brand": "Mahlkönig",
    "model": "EK43 (0-16)",
    "clicks": 16,
    "umPerClick": 50.2,
    "scraped": true
  },
  {
    "id": "hcg-mahlk-nig-ek43-1-11",
    "brand": "Mahlkönig",
    "model": "EK43 (1-11)",
    "clicks": 11,
    "umPerClick": 73,
    "scraped": true
  },
  {
    "id": "hcg-mahlk-nig-ek43-s",
    "brand": "Mahlkönig",
    "model": "EK43 S",
    "clicks": 16,
    "umPerClick": 50.2,
    "scraped": true
  },
  {
    "id": "hcg-mahlk-nig-gh2-hc880",
    "brand": "Mahlkönig",
    "model": "GH2 (HC880)",
    "clicks": 17,
    "umPerClick": 65.3,
    "scraped": true
  },
  {
    "id": "hcg-mahlk-nig-vta-6s",
    "brand": "Mahlkönig",
    "model": "VTA 6S",
    "clicks": 13,
    "umPerClick": 73.1,
    "scraped": true
  },
  {
    "id": "hcg-mahlk-nig-vta-6s-w",
    "brand": "Mahlkönig",
    "model": "VTA 6S W",
    "clicks": 13,
    "umPerClick": 73.1,
    "scraped": true
  },
  {
    "id": "hcg-mahlk-nig-x54",
    "brand": "Mahlkönig",
    "model": "X54",
    "clicks": 35,
    "umPerClick": 25.9,
    "scraped": true
  },
  {
    "id": "hcg-melitta-molino",
    "brand": "Melitta",
    "model": "Molino",
    "clicks": 17,
    "umPerClick": 64.7,
    "scraped": true
  },
  {
    "id": "hcg-moccamaster-km5",
    "brand": "Moccamaster",
    "model": "KM5",
    "clicks": 9,
    "umPerClick": 133.3,
    "scraped": true
  },
  {
    "id": "hcg-oxo-conical-burr-coffee-grinder",
    "brand": "OXO",
    "model": "Conical Burr Coffee Grinder",
    "clicks": 15,
    "umPerClick": 73.3,
    "scraped": true
  },
  {
    "id": "hcg-porlex-mini-ii",
    "brand": "Porlex",
    "model": "Mini II",
    "clicks": 24,
    "umPerClick": 58.3,
    "scraped": true
  },
  {
    "id": "hcg-rok-grindergc",
    "brand": "ROK",
    "model": "GrinderGC",
    "clicks": 25,
    "umPerClick": 40.4,
    "scraped": true
  },
  {
    "id": "hcg-timemore-c2-fold",
    "brand": "Timemore",
    "model": "C2 Fold",
    "clicks": 30,
    "umPerClick": 31.7,
    "scraped": true
  },
  {
    "id": "hcg-timemore-c2-max",
    "brand": "Timemore",
    "model": "C2 Max",
    "clicks": 30,
    "umPerClick": 31.7,
    "scraped": true
  },
  {
    "id": "hcg-timemore-c2-max-pro",
    "brand": "Timemore",
    "model": "C2 Max Pro",
    "clicks": 30,
    "umPerClick": 31.7,
    "scraped": true
  },
  {
    "id": "hcg-timemore-c3-pro",
    "brand": "Timemore",
    "model": "C3 Pro",
    "clicks": 25,
    "umPerClick": 38,
    "scraped": true
  },
  {
    "id": "hcg-timemore-nano",
    "brand": "Timemore",
    "model": "Nano",
    "clicks": 30,
    "umPerClick": 27.5,
    "scraped": true
  },
  {
    "id": "hcg-varia-vs3-gen-2",
    "brand": "Varia",
    "model": "VS3 (Gen 2)",
    "clicks": 19,
    "umPerClick": 73.7,
    "scraped": true
  },
  {
    "id": "hcg-wilfa-svart",
    "brand": "Wilfa",
    "model": "Svart",
    "clicks": 18,
    "umPerClick": 61.1,
    "scraped": true
  },
  {
    "id": "hcg-wilfa-svart-aroma",
    "brand": "Wilfa",
    "model": "Svart Aroma",
    "clicks": 18,
    "umPerClick": 61.1,
    "scraped": true
  },
  {
    "id": "hcg-wilfa-uniform",
    "brand": "Wilfa",
    "model": "Uniform",
    "clicks": 41,
    "umPerClick": 24.6,
    "scraped": true
  }
]
